# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Hell_Player(object):
    def setupUi(self, Hell_Player):
        Hell_Player.setObjectName("Hell_Player")
#        Hell_Player.resize(549, 440)
        Hell_Player.setGeometry(600, 220, 635, 340)
        Hell_Player.setMinimumSize(QtCore.QSize(500, 340))
        Hell_Player.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        Hell_Player.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayout = QtWidgets.QGridLayout(Hell_Player)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.playlist_frame = QtWidgets.QFrame(Hell_Player)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlist_frame.sizePolicy().hasHeightForWidth())
        self.playlist_frame.setSizePolicy(sizePolicy)
        self.playlist_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.playlist_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.playlist_frame.setProperty("setVisible", False)
        self.playlist_frame.setObjectName("playlist_frame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.playlist_frame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableWidget = QtWidgets.QTableWidget(self.playlist_frame)
        self.tableWidget.setMouseTracking(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_11.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.playlist_frame, 4, 1, 2, 2)
        self.frame_5 = QtWidgets.QFrame(Hell_Player)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 339))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 85))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ShowPL = QtWidgets.QPushButton(self.frame_2)
        self.ShowPL.setMaximumSize(QtCore.QSize(16777215, 15))
        self.ShowPL.setObjectName("ShowPL")
        self.gridLayout_12.addWidget(self.ShowPL, 2, 0, 1, 1)
        self.HidePL = QtWidgets.QPushButton(self.frame_2)
        self.HidePL.setMaximumSize(QtCore.QSize(16777215, 15))
        self.HidePL.setProperty("setVisible", False)
        self.HidePL.setObjectName("HidePL")
        self.gridLayout_12.addWidget(self.HidePL, 3, 0, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 49))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 49))
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(90, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.song_sec = QtWidgets.QLCDNumber(self.frame_4)
        self.song_sec.setGeometry(QtCore.QRect(40, 0, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.song_sec.sizePolicy().hasHeightForWidth())
        self.song_sec.setSizePolicy(sizePolicy)
        self.song_sec.setStyleSheet("color: rgb(53, 117, 255);")
        self.song_sec.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.song_sec.setDigitCount(2)
        self.song_sec.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.song_sec.setObjectName("song_sec")
        self.song_min = QtWidgets.QLCDNumber(self.frame_4)
        self.song_min.setGeometry(QtCore.QRect(-10, -10, 61, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.song_min.sizePolicy().hasHeightForWidth())
        self.song_min.setSizePolicy(sizePolicy)
        self.song_min.setStyleSheet("color: rgb(53, 117, 255);")
        self.song_min.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.song_min.setSmallDecimalPoint(False)
        self.song_min.setDigitCount(4)
        self.song_min.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.song_min.setObjectName("song_min")
        self.horizontalLayout.addWidget(self.frame_4)
        self.gridLayout_12.addWidget(self.frame_21, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_12.addWidget(self.widget_2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 3, 1, 2, 1, QtCore.Qt.AlignBottom)
        self.frame = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 94))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 86))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_8.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.nextButton = QtWidgets.QPushButton(self.widget_3)
        self.nextButton.setMinimumSize(QtCore.QSize(63, 50))
        self.nextButton.setMaximumSize(QtCore.QSize(63, 50))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout_8.addWidget(self.nextButton, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_3, 0, 3, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_6.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.playButton = QtWidgets.QPushButton(self.widget_4)
        self.playButton.setMinimumSize(QtCore.QSize(63, 50))
        self.playButton.setMaximumSize(QtCore.QSize(63, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(18)
        self.playButton.setFont(font)
        self.playButton.setObjectName("playButton")
        self.gridLayout_6.addWidget(self.playButton, 0, 0, 1, 1)
        self.pauseButton = QtWidgets.QPushButton(self.widget_4)
        self.pauseButton.setMinimumSize(QtCore.QSize(63, 50))
        self.pauseButton.setMaximumSize(QtCore.QSize(63, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        self.pauseButton.setFont(font)
        self.pauseButton.setFlat(False)
        self.pauseButton.setProperty("setVisible", False)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout_6.addWidget(self.pauseButton, 1, 0, 1, 1)
        self.pauseButton.raise_()
        self.playButton.raise_()
        self.gridLayout_2.addWidget(self.widget_4, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.prevButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevButton.sizePolicy().hasHeightForWidth())
        self.prevButton.setSizePolicy(sizePolicy)
        self.prevButton.setMinimumSize(QtCore.QSize(63, 50))
        self.prevButton.setMaximumSize(QtCore.QSize(63, 50))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.prevButton.setFont(font)
        self.prevButton.setObjectName("prevButton")
        self.gridLayout_7.addWidget(self.prevButton, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 2, 1, 1, 1, QtCore.Qt.AlignTop)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(94, 184))
        self.frame_8.setMaximumSize(QtCore.QSize(94, 184))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(40, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(40, 152))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.volumeSlider = QtWidgets.QSlider(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
        self.volumeSlider.setSizePolicy(sizePolicy)
        self.volumeSlider.setStyleSheet("color: rgb(2, 2, 2);")
        self.volumeSlider.setMaximum(51)
        self.volumeSlider.setSingleStep(1)
        self.volumeSlider.setPageStep(9)
        self.volumeSlider.setProperty("value", 24)
        self.volumeSlider.setOrientation(QtCore.Qt.Vertical)
        self.volumeSlider.setObjectName("volumeSlider")
        self.gridLayout_14.addWidget(self.volumeSlider, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_9, 0, 1, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(54, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_15.setContentsMargins(-1, -1, 20, -1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_15.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_10, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.muteCheckBox = QtWidgets.QCheckBox(self.frame_3)
        self.muteCheckBox.setMinimumSize(QtCore.QSize(90, 32))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.muteCheckBox.setFont(font)
        self.muteCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.muteCheckBox.setObjectName("muteCheckBox")
        self.gridLayout_16.addWidget(self.muteCheckBox, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_3, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame_8, 2, 2, 3, 1, QtCore.Qt.AlignTop)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 140))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setVerticalSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.song_title_field = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.song_title_field.sizePolicy().hasHeightForWidth())
        self.song_title_field.setSizePolicy(sizePolicy)
        self.song_title_field.setMinimumSize(QtCore.QSize(0, 36))
        self.song_title_field.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.song_title_field.setFont(font)
        self.song_title_field.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.song_title_field.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.song_title_field.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.song_title_field.setAutoFillBackground(False)
        self.song_title_field.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.song_title_field.setText("")
        self.song_title_field.setFrame(False)
        self.song_title_field.setAlignment(QtCore.Qt.AlignCenter)
        self.song_title_field.setReadOnly(True)
        self.song_title_field.setObjectName("song_title_field")
        self.gridLayout_17.addWidget(self.song_title_field, 0, 0, 1, 1)
        self.album_name_field = QtWidgets.QLineEdit(self.frame_7)
        self.album_name_field.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.album_name_field.setFont(font)
        self.album_name_field.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.album_name_field.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.album_name_field.setFrame(False)
        self.album_name_field.setAlignment(QtCore.Qt.AlignCenter)
        self.album_name_field.setReadOnly(True)
        self.album_name_field.setObjectName("album_name_field")
        self.gridLayout_17.addWidget(self.album_name_field, 1, 0, 1, 1)
        self.artist_name_field = QtWidgets.QLineEdit(self.frame_7)
        self.artist_name_field.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.artist_name_field.setFont(font)
        self.artist_name_field.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.artist_name_field.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.artist_name_field.setFrame(False)
        self.artist_name_field.setAlignment(QtCore.Qt.AlignCenter)
        self.artist_name_field.setReadOnly(True)
        self.artist_name_field.setObjectName("artist_name_field")
        self.gridLayout_17.addWidget(self.artist_name_field, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_7, 0, 0, 1, 3)
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 13))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 13))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.progressBar = QtWidgets.QSlider(self.frame_11)
        self.progressBar.setMaximum(100)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_11, 1, 0, 1, 3, QtCore.Qt.AlignTop)
        self.frame_51 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_51.sizePolicy().hasHeightForWidth())
        self.frame_51.setSizePolicy(sizePolicy)
        self.frame_51.setMinimumSize(QtCore.QSize(86, 96))
        self.frame_51.setMaximumSize(QtCore.QSize(96, 135))
        self.frame_51.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_51)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.open_folder = QtWidgets.QPushButton(self.frame_51)
        self.open_folder.setMaximumSize(QtCore.QSize(88, 16777215))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        self.open_folder.setFont(font)
        self.open_folder.setObjectName("open_folder")
        self.gridLayout_10.addWidget(self.open_folder, 0, 0, 1, 1)
        self.playlistButton = QtWidgets.QPushButton(self.frame_51)
        self.playlistButton.setMaximumSize(QtCore.QSize(88, 16777215))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        self.playlistButton.setFont(font)
        self.playlistButton.setObjectName("playlistButton")
        self.gridLayout_10.addWidget(self.playlistButton, 1, 0, 1, 1)
        self.addfilesButton = QtWidgets.QPushButton(self.frame_51)
        self.addfilesButton.setMaximumSize(QtCore.QSize(88, 16777215))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        self.addfilesButton.setFont(font)
        self.addfilesButton.setObjectName("addfilesButton")
        self.gridLayout_10.addWidget(self.addfilesButton, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_51, 2, 0, 2, 1, QtCore.Qt.AlignTop)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 49))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 49))
        self.frame_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shuffle_box = QtWidgets.QCheckBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shuffle_box.sizePolicy().hasHeightForWidth())
        self.shuffle_box.setSizePolicy(sizePolicy)
        self.shuffle_box.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.shuffle_box.setFont(font)
        self.shuffle_box.setMouseTracking(False)
        self.shuffle_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shuffle_box.setTristate(False)
        self.shuffle_box.setObjectName("shuffle_box")
        self.verticalLayout_2.addWidget(self.shuffle_box)
        self.gridLayout_4.addWidget(self.frame_6, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 0, 1, 1, 2)

        self.retranslateUi(Hell_Player)
        self.tableWidget.cellDoubleClicked['int','int'].connect(self.playButton.click)
        self.playButton.clicked.connect(self.playButton.hide)
        self.playButton.clicked.connect(self.pauseButton.show)
        self.pauseButton.clicked.connect(self.pauseButton.hide)
        self.pauseButton.clicked.connect(self.playButton.show)
        self.ShowPL.clicked.connect(self.HidePL.show)
        self.ShowPL.clicked.connect(self.ShowPL.hide)
        self.ShowPL.clicked.connect(self.playlist_frame.show)
        self.HidePL.clicked.connect(self.HidePL.hide)
        self.HidePL.clicked.connect(self.ShowPL.show)
        self.HidePL.clicked.connect(self.playlist_frame.hide)
        self.tableWidget.itemDoubleClicked['QTableWidgetItem*'].connect(self.playButton.click)
        self.volumeSlider.valueChanged['int'].connect(self.volumeSlider.setValue)
        self.progressBar.sliderMoved['int'].connect(self.progressBar.setValue)
        QtCore.QMetaObject.connectSlotsByName(Hell_Player)
        Hell_Player.setTabOrder(self.open_folder, self.playlistButton)
        Hell_Player.setTabOrder(self.playlistButton, self.prevButton)
        Hell_Player.setTabOrder(self.prevButton, self.playButton)
        Hell_Player.setTabOrder(self.playButton, self.pauseButton)
        Hell_Player.setTabOrder(self.pauseButton, self.nextButton)
        Hell_Player.setTabOrder(self.nextButton, self.volumeSlider)
        Hell_Player.setTabOrder(self.volumeSlider, self.shuffle_box)
        Hell_Player.setTabOrder(self.shuffle_box, self.HidePL)
        Hell_Player.setTabOrder(self.HidePL, self.ShowPL)
        Hell_Player.setTabOrder(self.ShowPL, self.muteCheckBox)
        Hell_Player.setTabOrder(self.muteCheckBox, self.tableWidget)

    def retranslateUi(self, Hell_Player):
        _translate = QtCore.QCoreApplication.translate
        Hell_Player.setWindowTitle(_translate("Hell_Player", "Hell Player"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Hell_Player", "#"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Hell_Player", "Title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Hell_Player", "Artist"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Hell_Player", "Album"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Hell_Player", "Year"))
        self.ShowPL.setText(_translate("Hell_Player", "Show"))
        self.HidePL.setText(_translate("Hell_Player", "Hide"))
        self.nextButton.setText(_translate("Hell_Player", ">>"))
        self.playButton.setText(_translate("Hell_Player", ">"))
        self.pauseButton.setText(_translate("Hell_Player", "||"))
        self.prevButton.setText(_translate("Hell_Player", "<<"))
        self.label.setText(_translate("Hell_Player", "V\n"
"o\n"
"l\n"
"u\n"
"m\n"
"e"))
        self.muteCheckBox.setText(_translate("Hell_Player", "Mute"))
        self.open_folder.setText(_translate("Hell_Player", "Folder"))
        self.playlistButton.setText(_translate("Hell_Player", "Playlist"))
        self.addfilesButton.setText(_translate("Hell_Player", "Add files"))
        self.shuffle_box.setText(_translate("Hell_Player", "Shuffle"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Hell_Player = QtWidgets.QWidget()
    ui = Hell_Player()
    ui.setupUi(Hell_Player)
    Hell_Player.show()
    sys.exit(app.exec_())

